version: "3"
services:
  worker:
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      CONFIGOR_ENV_PREFIX: "APP"
      APP_DB_PATH: ./db.sqlite
      APP_DB_RESETONSTART: "true"
      APP_SERVER_URL: "http://localhost:3000"
      APP_SERVER_PORT: ":3000"
      APP_SERVER_CORS: "[\"*\"]"

